dist: bionic
before_script:
  - wget https://opennmt-models.s3.amazonaws.com/transliteration-aren-all.tar.gz
  - tar xf transliteration-aren-all.tar.gz -C tests/data/models/

matrix:
  include:
    - sudo: true
      language: cpp
      compiler:
        - gcc
      addons:
        apt:
          packages:
            - cmake
      before_install:
        # Intel MKL
        - wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
        - sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
        - sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
        - sudo apt-get update
        - sudo apt-get install -y intel-mkl-64bit-2020.0-088
      install:
        - mkdir build
        - cd build
        - cmake -DCMAKE_INSTALL_PREFIX=$PWD/../install -DWITH_TESTS=ON ..
        - make -j2 install
        - cd ..
      script:
        - build/tests/ctranslate2_test tests/data

    - language: python
      python:
        - "3.7"
      env:
        - TWINE_REPOSITORY_URL="https://upload.pypi.org/legacy/"
      services:
        - docker
      before_install:
        - docker run -v $PWD:/root -w /root quay.io/pypa/manylinux2010_x86_64 bash /root/python/tools/build_wheel.sh
        - pip install -r python/tests/requirements.txt
        - pip uninstall -y ctranslate2
        - pip install twine
      install:
        - pip install python/wheelhouse/*cp37*.whl
      script:
        - pytest python/tests/test.py
      after_success:
        - |
              if [[ -n $TRAVIS_TAG ]]; then
                  twine upload python/wheelhouse/*.whl
              fi
